Repository timescale/promscale_extension, pull requests merged in 2022-08, with the labels that each got.

#451 Run upgrade tests across released Docker containers
  Cargo.lock
  RELEASING.md
  e2e/Cargo.toml
  e2e/tests/config/mod.rs
  e2e/tests/upgrade-test.rs
  test-common/src/postgres_container/mod.rs
Labels: epic/developer-issues

#462 Another attempt at fixing the bug with tag_v type
  CHANGELOG.md
  docs/sql-api.md
  migration/idempotent/007-tracing-tags.sql
  migration/incremental/031-remove-superfluous-tag_v-ops.sql
Labels: Bug, epic/developer-issues

#489 Updating releasing instructions
  RELEASING.md
Labels: Documentation

#499 updating releasing instructions
  RELEASING.md
Labels: Documentation
