Repository timescale/promscale_extension, pull requests merged in 2022-07, with the labels that each got.

#388 Remove `_bytes_total` calculations from telemetry.
  CHANGELOG.md
  migration/idempotent/010-telemetry.sql
Labels: Performance

#396 Adds ability to configure epoch duration
  CHANGELOG.md
  migration/idempotent/001-base.sql
  sql-tests/testdata/defaults.sql
  sql-tests/tests/snapshots/tests__testdata__defaults.sql.snap
Labels: Performance

#420 drop the get_confirmed_unused_series function so we can rename a param
  migration/incremental/030-remove-get-confirmed-unused-series.sql
Labels: Bug

#425 Allow tests to specify docker image
  test-common/src/lib.rs
Labels: Test

#442 Remove unnecessary warning
  templates/incremental-wrapper.sql
Labels: Bug

#444 Bump to our fork of pgx v0.4.5
  .cargo/config
  .cargo/pgx-linker-script.sh
  .github/workflows/ci.yaml
  .github/workflows/lint.yaml
  Cargo.lock
  Cargo.toml
  INSTALL.md
  Makefile
  alpine.Dockerfile
  dev.Dockerfile
  devenv.sh
  dist/deb.dockerfile
  dist/rpm.dockerfile
  ha.Dockerfile
  install-cargo-pgx.sh
  src/aggregates/prom_rate.rs
  src/bin/sql-generator.rs
  templates/promscale.control
Labels: epic/developer-issues

#445 Dockerless SQL tests
  .github/workflows/docker.yaml
  Cargo.toml
  DEVELOPMENT.md
  Makefile
  sql-tests/README.md
  sql-tests/testdata/create_ingest_temp_table.sql
  sql-tests/testdata/defaults.sql
  sql-tests/testdata/drop_metric.sql
  sql-tests/testdata/info_view.sql
  sql-tests/testdata/large_tracing_tags_support.sql
  sql-tests/testdata/metric-retention.sql
  sql-tests/testdata/ps_trace.delete_all_traces.sql
  sql-tests/testdata/support.sql
  sql-tests/testdata/tag_map.sql
  sql-tests/testdata/trace_compression.sql
  sql-tests/testdata/views.sql
  sql-tests/tests/snapshots/tests__testdata__defaults.sql.snap
  sql-tests/tests/snapshots/tests__testdata__info_view.sql.snap
  sql-tests/tests/snapshots/tests__testdata__large_tracing_tags_support.sql.snap
  sql-tests/tests/snapshots/tests__testdata__ps_trace.delete_all_traces.sql.snap
  sql-tests/tests/snapshots/tests__testdata__support.sql.snap
  sql-tests/tests/snapshots/tests__testdata__tag_map.sql.snap
  sql-tests/tests/snapshots/tests__testdata__trace_compression.sql.snap
  sql-tests/tests/snapshots/tests__testdata__views.sql.snap
  sql-tests/tests/tests.rs
  test-common/src/local_postgres_instance.rs
  test-common/src/test_container_instance.rs
Labels: epic/developer-issues
