Repository timescale/promscale_extension, pull requests merged in 2022-05, with the labels that each got.

#242 Correct the privileges on tracing tables
  migration/incremental/015-tracing-redesign.sql
Labels: Bug

#272 Ensure that frozen incremental files are not modified
  Cargo.lock
  e2e/Cargo.toml
  e2e/tests/incremental-freeze-test.rs
Labels: Test

#310 Use text instead of name for function args
  migration/idempotent/001-base.sql
  migration/idempotent/006-exemplar.sql
  migration/idempotent/013-tracing-maintenance.sql
Labels: Performance
