Repository timescale/promscale_extension, pull requests merged in 2022-04, with the labels that each got.

#174 Optimize maintenance jobs by using TS catalog tables
  migration/idempotent/001-base.sql
Labels: Performance

#181 Dump/Restore Test
  Cargo.lock
  e2e/Cargo.toml
  e2e/scripts/init.sql
  e2e/scripts/snapshot.sql
  e2e/tests/dump-restore-test.rs
Labels: Test

#190 Prevent duplicate or missing numeric prefixes
  build.rs
Labels: Improvement

#191 Better data alignment for tracing tables
  migration/migration/015-tracing-compression.sql
Labels: Performance

#185 Dump/restore fixes
  .gitignore
  Cargo.lock
  build.rs
  e2e/Cargo.toml
  e2e/scripts/init.sql
  e2e/scripts/post-restore.sql
  e2e/scripts/post-snapshot.sql
  e2e/scripts/pre-dump.sql
  e2e/scripts/pre-restore.sql
  e2e/scripts/snapshot.sql
  e2e/testdata/defaults.sql
  e2e/tests/dump-restore-test.rs
  e2e/tests/snapshots/golden_tests__golden_test_testdata_defaults_sql.snap
  e2e/tests/test.rs
  migration/idempotent/001-base.sql
  migration/idempotent/004-ha.sql
  migration/idempotent/008-tracing-functions.sql
  migration/idempotent/010-telemetry.sql
  migration/idempotent/011-maintenance.sql
  migration/idempotent/012-trace-id-functions.sql
  migration/idempotent/013-remote-commands.sql
  migration/idempotent/014-apply-config.sql
  migration/incremental/002-utils.sql
  migration/incremental/006-tables.sql
  migration/incremental/008-install-uda.sql
  migration/incremental/012-tracing.sql
  migration/incremental/015-tracing-compression.sql
  migration/incremental/019-prom-installation-info.sql
  migration/incremental/020-series-partitions.sql
  migration/incremental/021-initial-default.sql
  sql/promscale--0.0.0.sql
Labels: Bug
